### ISSUE TITLE
What service? Why do I need an account?

### ISSUE THREAD

**Issue by spth** [Cryptonomic/Tezori#643]
I've installed Galleon, created a wallet.

According to https://tezos.com/get-started#store-and-use-basics and https://galleon-wallet.tech, galleon is a wallet.
I don't understand, why I was shows terms of service after starting Galleon for the first time. Galleon is software under the GPL, so what are those terms about? What is this service? Why would I want or need it? Why does Galleon ask me to create an account after wallet creation. Account where? for what?

**Comment by anonymoussprocket** [comment]
Galleon is a distribution of Tezori. The latter is indeed an open-source, GPLv3 project. Cryptonomic makes this release available to the community members who do not want to build their own. Since Cryptonomic is distributing this software there is a EULA and related prompts in the application.

The account here is the account on the chain. No information about your private keys or other personal information is set back to Cryptonomic services.

Please reach out via our support channels on email or telegram with further questions.
